FORMAT: 1A
HOST: http://emp.vts.it/vts-ws-rest-api

# ws2017

Service Oriented Architecture specified for the WS project.


## Vendors [/vendors]

### Vendors collection [GET]

Returns the list of vendors.

This action is available to `WS_USER_READ` role.

+ Response 200 (application/json)
  + Attributes (VendorListResult)

## Departments [/departments]

### Departments collection [GET]

Returns the list of departments.

This action is available to `WS_USER_READ` role.

+ Response 200 (application/json)
  + Attributes (DepartmentListResult)

## Locations [/locations]

### Locations collection [GET]

Returns the list of locations.

This action is available to `WS_USER_READ` role.

+ Response 200 (application/json)
  + Attributes (LocationListResult)

## Employee types [/employeetypes]

### Employee types collection [GET]

Returns the list of employee types.

This action is available to `WS_USER_READ` role.

+ Response 200 (application/json)
  + Attributes (EmployeeTypeListResult)

#######################
# Group Employees
#######################

## Employees collection [/employees]

### List of Employees [GET]

Returns the list of VTS employees and Vendor Employees.

This action is available to `WS_USER_READ` role.

+ Response 200 (application/json)
  + Attributes (EmployeeListResult)


## Employee [/employees/{userId}]

+ Parameters
    + userId: US099971 (required, string) - usercode of the user

+ Attributes (Employee1)

### Read Employee [GET]

Read detail for the specified employee.

This action is available only to `WS_USER_READ` roles.


+ Response 200 (application/json)

    + Attributes (Employee1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body
  
### Update Employee job role [PUT /employees/{userId}/jobrole]

Updates job role for the specified employee.

This action is available only to `WS_USER_WRITE` roles.

+ Parameters
    + userId: US099971 (required, number) - usercode of the employee

+ Request (application/json)
  + Attributes
      + jobRole: `new job role` (required, string) - new job role (max 512 char)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body
  
### Update Employee profession [PUT /employees/{userId}/profession]

Updates profession for the specified employee.

This action is available only to `WS_USER_WRITE` roles.

+ Parameters
    + userId: US099971 (required, number) - usercode of the employee

+ Request (application/json)
  + Attributes
      + profession: `new profession` (required, string) - new profession (max 512 char)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body
  
  
#######################
# Group Users
#######################


## Check user credentials [POST /users/checkUser{?userId}{?password}]

Check passed credentials 

This action is available only to `WS_USER_READ` roles.

+ Request (application/json)
  + Attributes
      + userId: `abc@domain.com` (required, string) - userId 
      + password: xxxxxch x (required, string) - password


+ Response 200 (application/json)
  + Attributes
      + userCode: `US099971` - User ID IAM

+ Response 200 (application/json)
  + Attributes
      + error: `Username and password check failed` 

#######################
# Data Structures
#######################

## PaginationData3 (object)
+ paginationData (object, required) - Informations required for pagination
    + count: 3 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 999999999 (number, required) - size of the slice

## PaginationData4 (object)
+ paginationData (object, required) - Informations required for pagination
    + count: 4 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 999999999 (number, required) - size of the slice


## Vendor1 (object)
+ id: 1 (number) - vendor id
+ functionId: `VMP_VND` (enum[string],required) - function code VMP_VND=Vendors,VMP_SUB=Subcontractors
+ masterCode : `4000308` (required, string) - master code
+ name: `A1 TELEKOM AUSTRIA AG` (required, string) - company name
+ status (VendorStatus1)  (required, string) - status object
+ code : `4000308` (required, string) - same as master code

## Vendor2 (object)
+ id: 2 (required, number)
+ functionId: `VMP_VND` (enum[string],required) - function code VMP_VND=Vendors,VMP_SUB=Subcontractors
+ masterCode : `4000477` (required, string)
+ name: `ADECCO ITALIA SPA` (required, string)
+ status (VendorStatus1)
+ code : `4000477` 


## Vendor3 (object)
+ id: 3 (required, number)
+ functionId: `VMP_VND` (enum[string],required) - function code VMP_VND=Vendors,VMP_SUB=Subcontractors
+ masterCode : `4000477` (required, string)
+ name: `SODEXO` (required, string)
+ status (VendorStatus1)
+ code : `4000477` 

## VendorListResult (object)
+ results (array[Vendor1, Vendor2, Vendor3], required) - array of Vendors
+ Include PaginationData3

## VendorStatus1 (object)
+ id: `001` (required, string) - status code
+ description: `Active` - status description
+ disposal: false - indicate if status is related to disposal of entity


## Department1 (object)
+ ouCode: XL78506 (string) - department code 
+ ouName: Finance and Planning (string) - department name
+ status: Y (string) - ou status in current Hierarchical active revision (Y=active, N=inactive) 
+ parentOuCode: XL78486 (string) - parent department code in current Hierarchical active revision 
+ managerId: 33 (number) - department manager internal employee id (in current Hierarchical active revision) 
+ managerUserCode : XL99999 (string) - department manager usercode (in current Hierarchical active revision)

## Department2 (object)
+ id: XL78521
+ description: Unit Network Italy
+ status: N
+ parentOuCode: 
+ managerId:  
+ managerUserCode : 

## Department3 (object)
+ id: XL78522
+ description: Unit Network Germany
+ status: Y
+ parentOuCode: XL78486 
+ managerId: 25 
+ managerUserCode : XL99998 

## Department4 (object)
+ id: XL78531
+ description: Service Reliability Germany
+ status: Y
+ parentOuCode: XL78486 
+ managerId: 322 
+ managerUserCode : XL99997 


## DepartmentListResult (object)
+ results (array[Department1, Department2, Department3, Department4], required) - array of Departments
+ Include PaginationData4


## Location1 (object)
+ id: 12 (number) - location code
+ street: Via del plebiscito 25 (string) - location address
+ city: Padova (string) - location city
+ state: PD (string) - location state
+ zip: 35100 (string) - location zip
+ country: Italy (string) - location country description

## Location2 (object)
+ id: 20
+ street: Via Mazzini 25
+ city: Roma
+ state: RM
+ zip: 00195
+ country: Italy

## Location3 (object)
+ id: 4
+ street: Via Garibaldi 5
+ city: Milano
+ state: RM
+ zip: 23445
+ country: Italy

## LocationListResult (object)
+ results (array[Location1, Location2, Location3], required) - array of Locations
+ Include PaginationData3

## EmployeeType1 (object)
+ id: EXT (string) - Employee type code
+ description: Extended Team IBM (string) - Employee type description

## EmployeeType2 (object)
+ id: LOA
+ description: IBM LOA

## EmployeeType3 (object)
+ id: EMP
+ description: V-TS Employee

## EmployeeTypeListResult (object)
+ results (array[EmployeeType1, EmployeeType2, EmployeeType3], required) - array of Employee types
+ Include PaginationData3


## Employee1 (object)
+ id: 1 (number) - employee internal id
+ firstName: Fabio (string) - first name
+ lastName: Gabbia (string) - last name 
+ userCode: US099974 (string) - user id 
+ email: example@it.ibm.com (string) - primary email
+ altInternetAddress : `example@v-tsservices.unicredit.eu` (string) - secondary email 
+ notesAddress : `example/Italy/V-TServices/IJV` (string) - notes address 
+ employeeType: Extended Team IBM (string) - employee type description
+ startDate: `2016-04-01` (string) - hiring date
+ dismissDate: `2016-04-01` (string) - dismiss date
+ ouCode: XJ99004 (string) - Organization unit code (in current uo revision)
+ ouName: Austria HR (string) - Organization unit name (in current uo revision)
+ isManager: false (boolean) - true if employee is manager of the OU 
+ managerUserCode : US099976 (string) - user code of the manager
+ status: INACTIVE (string) - status ACTIVE/INACTIVE 
+ vendorCode: 50000001 (string) - master code of vendor (evaluated only for vendor employees)
+ locationCode: (number) - location id (evaluated only for vts employees)

## Employee2 (object)
+ id: 2 (number) - employee internal id
+ firstName: Antonio (string) - first name
+ lastName: Cortese (string) - last name 
+ userCode: US099970 (string) - user id 
+ email: `antonio.cortese_v-tsservices@it.ibm.com` (string) - primary email
+ altInternetAddress : `antonio.cortese@v-tsservices.unicredit.eu` (string) - secondary email 
+ notesAddress : (string) - notes address 
+ employeeType: `V-TS Employee` (string) - employee type description
+ startDate: `2010-02-01` (string) - hiring date
+ dismissDate: (string) - dismiss date
+ ouCode: XL78513 (string) - Organization unit code (in current uo revision)
+ ouName: Service Line Network SIL (string) - Organization unit name (in current uo revision)
+ isManager: true (boolean) - true if employee is manager of the OU 
+ managerUserCode : US099976 (string) - user code of the manager
+ status: ACTIVE (string) - status ACTIVE/INACTIVE 
+ vendorCode: (string) - master code of vendor (evaluated only for vendor employees)
+ locationCode: 3 (number) - location id (evaluated only for vts employees)

## Employee3 (object)
+ id: 3 (number) - employee internal id
+ firstName: Lucia (string) - first name
+ lastName: Del campo (string) - last name 
+ userCode: US099971 (string) - user id 
+ email: `lucia.delcampo_v-tsservices@it.ibm.com` (string) - primary email
+ altInternetAddress : `lucia.delcampo@v-tsservices.unicredit.eu` (string) - secondary email 
+ notesAddress : (string) - notes address 
+ employeeType: Extended Team IBM (string) - employee type description
+ startDate: `2005-06-01` (string) - hiring date
+ dismissDate: (string) - dismiss date
+ ouCode: XJ99011 (string) - Organization unit code (in current uo revision)
+ ouName: Austria Procurement (string) - Organization unit name (in current uo revision)
+ isManager: false (boolean) - true if employee is manager of the OU 
+ managerUserCode : US099976 (string) - user code of the manager
+ status: ACTIVE (string) - status ACTIVE/INACTIVE 
+ vendorCode: 50000002 (string) - master code of vendor (evaluated only for vendor employees)
+ locationCode: (number) - location id (evaluated only for vts employees)

## EmployeeListResult (object)
+ results (array[Employee1, Employee2, Employee3], required) - array of Employees
+ Include PaginationData3